version: '3.9'
services:
  api:
    build: ./API
    container_name: vistoria-api
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_SERVICE_ACCOUNT_FILE=/app/service-account.json
      - SPREADSHEET_ID=1OypeFbnDkBMWNYSqH36DJYtR8l4lapWwG9j44fdzTXw
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    restart: always

  frontend:
    build: .
    container_name: vistoria-frontend
    ports:
      - "80:80"
    depends_on:
      - api
